--TASK 1---------------------------------
DROP TABLE students;

CREATE TABLE students(
	studentID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    studentName VARCHAR(100) NOT NULL,
    marks NUMERIC(5,2) CHECK (marks >= 0)
);


INSERT INTO students (studentName, marks)
VALUES
	('John', 79),
	('Selena', 95.65),
	('Noah', 34.96)
	
UPDATE students
SET marks = 47
	WHERE studentName = 'John';

DELETE FROM students
WHERE marks<40;

SELECT * FROM students; 


--TASK 2-----------------------------------------

DROP TABLE accounts;

CREATE TABLE accounts (
	accountID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	accountName TEXT,
	balance NUMERIC(12, 2) CHECK (balance >=0)
);

INSERT INTO accounts (accountID, accountName, balance)
VALUES
(1, 'Account A', 5000),
(2, 'Account B', 2000)


--
DO $$
BEGIN
    -- Start transaction implicitly (DO runs in a transaction)

    -- Deduct from Account A
    UPDATE accounts
    SET balance = balance - 1000
    WHERE accountID = 1
      AND balance >= 1000;

    -- If no row updated → insufficient funds
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Insufficient balance in Account A';
    END IF;

    -- Add to Account B
    UPDATE accounts
    SET balance = balance + 1000
    WHERE accountID = 2;

EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Transaction failed. Rolling back.';
        RAISE;-- rethrow error → entire transaction rolls back
END $$;

---

SELECT * FROM accounts;

--TASK 3----------------------------------------------------------------

DROP TABLE employees;

CREATE TYPE department_type 
AS 
ENUM ('HR', 'IT', 'Sales');

CREATE TABLE employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    department department_type,
    salary NUMERIC(10,2)
);


INSERT INTO employees (name, department, salary) VALUES
('Alice',   'HR',    50000),
('Bob',     'IT',    70000),
('Charlie', 'IT',    60000),
('Diana',   'HR',    55000),
('Ethan',   'Sales', 45000);


SELECT *
FROM employees
WHERE salary > (
    SELECT AVG(salary)
    FROM employees
);


--TASK 4---------------------------------------------

SELECT department, COUNT(id) AS employee_count
FROM employees 
GROUP BY department ;



--TASK 5------------------------------------------------

SELECT 
    name,
    salary,
    DENSE_RANK() OVER (ORDER BY salary DESC) AS salary_rank
FROM employees;














	